apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: update-bundle-csv
spec:
  params:
    - name: snapshot-url
      description: "URL to fetch the latest snapshot of component images"
      default: "https://console.redhat.com/application-pipeline/workspaces/rhoai/applications/rhoai-operator/snapshots/rhoai-operator-qnbvm"
    - name: registry-replacemen
      description: "Target registry, e.g., registry.redhat.io"
      default: "registry.redhat.io"
    - name: repo-replacement
      description: "Repository path replacement"
      default: "registry/rhoai-path"
    - name: csv-file-path
      description: "Path to the bundle CSV file to update"
      default: "bundle/manifests/rhods-operator.clusterserviceversion.yaml"
  steps:
    - name: fetch-snapshot
      image: 'quay.io/your-registry/fetch-snapshot:latest'
      script: |
        # Fetch the latest snapshot of all components
        curl -s ${SNAPSHOT_URL} -o snapshot.json
        cat snapshot.json

    - name: process-images
      image: 'quay.io/your-registry/process-images:latest'
      script: |
        # Extract and replace image URIs in the CSV
        jq -r '.components[] | .image' snapshot.json | while read -r image; do
          new_image=$(echo $image | sed "s|registryproxy|${REGISTRY_REPLACEMENT}|; s|modh|${REPO_REPLACEMENT}|")
          sed -i "s|$image|$new_image|" ${CSV_FILE_PATH}
        done

    - name: update-csv
      image: 'quay.io/your-registry/update-csv:latest'
      script: |
        # Update the CSV file with the new image URIs
        echo "CSV file at ${CSV_FILE_PATH} has been updated with the latest images."
