name: Operator Processor

on:
  workflow_dispatch:
  push:
    branches:
      - 'rhoai-*'
    paths:
      - build/operator-nudging.yaml


env:
  GITHUB_ORG: rhoai-rhtap
  RESOLVE_CONFLICTS_FOR: build/operator-nudging.yaml

permissions:
  contents: write

jobs:
  operator-processor:
    if: ${{ github.event_name == 'workflow_dispatch' || ( github.event_name == 'push' && github.event.commits[0].author.name == 'konflux-internal-p02' ) }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout RBC repo
        uses: actions/checkout@v4
        with:
          repository: ${{ env.GITHUB_ORG }}/RHOAI-Build-Config
          ref: ${{ github.ref_name }}
          path: RBC
          sparse-checkout: |
            bundle/bundle-patch.yaml
          sparse-checkout-cone-mode: false
      - name: Sparse Checkout Notebooks
        uses: actions/checkout@v4
        with:
          repository: ${{ env.GITHUB_ORG }}/notebooks
          ref: ${{ github.ref_name }}
          path: notebooks
          sparse-checkout: |
            manifests
          sparse-checkout-cone-mode: false

      - name: List all files
        run: |
          echo "AUTHOR=$AUTHOR"
          cd notebooks
          tree
          cd ../RBC 
          tree

#      - name: Merge Feasibility Check
#        if: ${{ steps.changed-files.outputs.all_changed_files == 'build/operator-nudging.yaml' }}
#        id: merge-feasibility-check
#        run: |
#          # Declare variables
#          BASE_BRANCH=${GITHUB_BASE_REF:-${GITHUB_REF#refs/heads/}}
#          HEAD_BRANCH=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}
#          VERSION=v${BASE_BRANCH/rhoai-/}
#          SUFFIX=${VERSION/./-}
#          echo "SUFFIX=$SUFFIX"
#          echo "HEAD_BRANCH=$HEAD_BRANCH"
#          REGEX="^Update.*-$SUFFIX to [0-9a-z]{1,40}$"
#
#          FEASIBLE=No
#          #Check if PR title is as per the convention
#          if [[ "${{ github.event.pull_request.title }}" =~ $REGEX ]]
#          then
#            FEASIBLE=Yes
#            echo "It's a valid PR to merge!"
#          else
#            echo "Insta-merge not configured to merge this PR, skipping."
#          fi
#          echo "FEASIBLE=$FEASIBLE" >> $GITHUB_OUTPUT
#          echo "BASE_BRANCH=$BASE_BRANCH" >> $GITHUB_OUTPUT
#          echo "HEAD_BRANCH=$HEAD_BRANCH" >> $GITHUB_OUTPUT
#
#      - name: Generate github-app token
#        id: app-token
#        uses: getsentry/action-github-app-token@v2
#        with:
#          app_id: ${{ secrets.RHOAI_DEVOPS_APP_ID }}
#          private_key: ${{ secrets.RHOAI_DEVOPS_APP_PRIVATE_KEY }}
#
#      - uses: Wandalen/wretry.action@master
#        if: ${{ steps.merge-feasibility-check.outputs.FEASIBLE == 'Yes' }}
#        with:
#          action: red-hat-data-services/insta-merge@main
#          retry_condition: steps._this.outputs.code == 0
#          attempt_limit: 5
#          github_token: ${{ steps.app-token.outputs.token }}
#          with: |
#            upstream_repo: "https://github.com/${GITHUB_ORG}/rhods-operator.git"
#            upstream_branch: "${{ steps.merge-feasibility-check.outputs.BASE_BRANCH }}"
#            downstream_repo: "https://github.com/${GITHUB_ORG}/rhods-operator.git"
#            downstream_branch: "${{ steps.merge-feasibility-check.outputs.HEAD_BRANCH }}"
#            token: ${{ steps.app-token.outputs.token }}
#            resolve_conflicts_for: "${RESOLVE_CONFLICTS_FOR}"
#            merge_args: "--no-edit"
#            pr_url: "${{ github.event.pull_request.html_url }}"
